// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzezpynguvrdhzfvtgjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16ZXpweW5ndXZyZGh6ZnZ0Z2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODM4MTMsImV4cCI6MjA2Mzg1OTgxM30.o_r479krTuJiQ-l7Qul1nC1wq3KQJoXO-0hjUq-ps0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);